### ISSUE TITLE
self.g2ConfigMgr not defined

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2configtool#37]
Although `self.g2ConfigMgr` is used in 

https://github.com/Senzing/g2configtool/blame/issue-28.jae.1/G2ConfigTool.py#L136-L137

It isn't defined anywhere.

More than likely, it should be:

```python
                    self.g2_configmgr.addConfig(config_string, 'New default configuration added by G2ConfigTool.', addconfig_id)
                    self.g2_configmgr.setDefaultConfigID(addconfig_id)
```
using `self.g2_configmgr`.

**Comment by jbutcher21** [comment]
It is defined in the class __init__ function ...
self.g2_configmgr = G2ConfigMgr()
