### ISSUE TITLE
More user friendly reference commands

### ISSUE THREAD

**Issue by Lohrax** [Senzing/g2configtool#62]
G2Config is not only used to change the config, Data transformation users (ETL guys) use it to find and understand attributes/features.  Currently its difficult to do things like find an attribute/feature if you only know something about it but not the entire name, of if the features has multiple attributes that can be used in the ETL. 

Suggested additions are (the options should be combinable):
  listAttributes --minimal or listFeatures --minimal would provide only ID and Name
    example: listAttributes -m
    example return: "id":"11202","attribute":"MyId_NUMBER"
                                "id":"11203","attribute":"MyOtherId_NUMBER"
                               ........
    example: listFeatures -m (NOTE: this one is a bit more difficult, you would need feature name and feature elements)
    example return: "id": "4", "feature": "GENDER","elementList": [{"element": "GENDER"]}
                                "id": "6", "feature": "PHONE", "elementList": [{"element": "PHONE_AREA_CODE"}, {"element": "PHONE_NUM"}, {"element": "PHONE_EXT"}, {"element": "PHONE_LAST_10"}, {"element": "PHONE_LAST_5"}]
                               ........

  listAttributes --usable or listFeatures --usable only returns attributes where internal =no (attribute) or display = yes (feature)
    example: listFeatures -m -u
    example return: "id": "4", "feature": "GENDER","elementList": [{"element": "GENDER"]}
                                "id": "6", "feature": "PHONE", "elementList": [{"element": "PHONE_AREA_CODE"}, {"element": "PHONE_NUM"}, {"element": "PHONE_EXT"}]
                               ........

  listAttributes --search <value> (returns an attribute(s) that contains that string
    example: listAttributes -m -u -s  Date (search for "Date" and return minimal information and all attributes that are not internal )
    example return: "id": "1221", "attribute": "DATE_OF_BIRTH"
                                "id": "1261", "attribute": "DATE_OF_DEATH"
                                "id": "1323", "attribute": "PASSPORT_ISSUE_DT"
                                "id": "1324", "attribute": "PASSPORT_EXPIRE_DT"

I'm sure there are more that we could come up with, these were just ones that I ran into while working with a customer today.

**Comment by jbutcher21** [comment]
This is a won't do as there is already auto complete and all listings allow filtering.
