### ISSUE TITLE
addDataSource capitalization

### ISSUE THREAD

**Issue by Lohrax** [Senzing/g2configtool#63]
Currently if you add a new datasource G2ConfigTool creates the data source in all upper.  However if your data source in the JSON input file is mixed case the ingest fails.  This forces a user to convert all their data source names to upper even if they wanted them to be in lower case.  

If we are going to follow the process of not changing the data that they user has input then please add the ability to create a mixed case Data Source via addDataSource.

**Comment by jamietypovsky** [comment]
@antaenc can you do a review of all tools to make sure data source is treated case insensitive?

**Comment by antaenc** [comment]
This no longer appears to be a problem and is fixed in the engine.
